# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
   ACTIONS_ALLOW_UNSECURE_COMMANDS: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup_swift: 
    runs-on: ubuntu-latest
    steps:
    - name: Setup Swift
      uses: fwal/setup-swift@v1.3.0
      with:
        swift-version: "5.3.0"
    
  # This workflow contains a single job called "build"
  build:
    needs: setup_swift
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: swift build
  system_tests:
    needs: setup_swift
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift build
      - run: Tests/test.sh
  unit_tests:
    needs: setup_swift
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: swift build
      - run: swift test
